development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_DEV_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: tictactoeadv_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_BASE_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: tictactoeadv_production
